### ISSUE TITLE
Version 2.2 not available on terraform registry.

### ISSUE THREAD

**Issue by shiv4nsh** [terraform-aws-modules/terraform-aws-memory-db#11]
## Expected behavior

Version 2.2 should be available on [terraform registry](https://registry.terraform.io/modules/terraform-aws-modules/memory-db/aws/latest)

## Actual behavior

it is not 

### Terminal Output Screenshot(s)

![image](https://github.com/user-attachments/assets/f12ae811-9808-4a7f-9b6d-4bccec84c24b)

**Comment by antonbabenko** [comment]
Fixed
