### ISSUE TITLE
terraform-aws-memory-db: include lifecycle block to aws_memorydb_cluster to avoid possible downtimes

### ISSUE THREAD

**Issue by GeorgeDavis-TriumphTech** [terraform-aws-modules/terraform-aws-memory-db#4]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I am using the [terraform-aws-modules/terraform-aws-memory-db](terraform-aws-modules/terraform-aws-memory-db) module but I am seeing `creating` and `destroying` of the aws_memorydb_cluster, simultaneously. This might cause an abrupt breaking change for an application that relies on the MemoryDB cluster and could lead to app crashes, possibly longer downtimes.

## Describe the solution you'd like.
It would be great if had a `lifecycle` block (as shown below) on the `aws_memorydb_cluster` resource as well so we can reduce the amount of downtime for the application. We would still need to pass the newer cluster_endpoint_address downstream to dependent compute resources, like Lambda, EC2 and so on.

```terraform
lifecycle {
  create_before_destroy = true
}
```

The proposed change could reduce the amount of time for the application to come back online.

## Describe alternatives you've considered.
I would love to throw a `lifecycle` block on the module reference code in Terraform but lifecycle is not supported on modules yet. Refer https://github.com/hashicorp/terraform/issues/27360.

I am willing to fork the repository and make the changes and submit a PR, if the changes/feature request makes sense. 

Thank you for your contributions to the Terraform community!

**Comment by GeorgeDavis-TriumphTech** [comment]
@bryantbiggs Do you think this feature request would be helpful for module users? I would love to hear your comments. Thank you.

**Comment by bryantbiggs** [comment]
I'm trying to understand how this will avoid downtime? If the end result is always the deletion and re-creation of a DB, that still means downtime and data loss

**Comment by GeorgeDavis-TriumphTech** [comment]
Sorry for the delayed response. Having a replacement DB created before we destroy the existing DB in use would only require switching connection strings on the application end (say Lambda functions) and can be modified using Terraform. This would reduce the amount of downtime for the application as the Memory DB replacement slides in.

**Comment by bryantbiggs** [comment]
closing this for now unless there is further evidence that this is solving an issue
