### ISSUE TITLE
vector search enabled MemoryDB cluster via terraform module

### ISSUE THREAD

**Issue by filipecosta90** [terraform-aws-modules/terraform-aws-memory-db#7]
via aws-cli we can create the cluster with vector search enabeld by passing the parameter group `default.memorydb-redis7.search.preview`, as stated in:
```
To create a vector search enabled MemoryDB cluster, you can use the MemoryDB [create-cluster](https://docs.aws.amazon.com/cli/latest/reference/memorydb/create-cluster.html) command by passing an immutable parameter group default.memorydb-redis7.search.preview to enable the preview mode for vector search capabilities.
```

However, when I do that via terraform:
```

module "memory_db" {
  source = "terraform-aws-modules/memory-db/aws"


  engine_version            = "7.1"
  node_type                    = "db.r7g.2xlarge"
  num_shards                 = 1
  
  # Parameter group
  create_parameter_group = false
  parameter_group_family = "default.memorydb-redis7.search.preview"
 (...)
 (...)
}

```

it's not enabled. 
I've confirmed it:
```
-ERR Command not enabled, instance needs to be configured for Public Preview for Vector Similarity Search
```

**Comment by jeferramirez** [comment]
I have the same problem, can anyone help us, please?

**Comment by bryantbiggs** [comment]
I don't think you are following the docs correctly, I think you need to do:

```hcl
module "memory_db" {
  source = "terraform-aws-modules/memory-db/aws"


  engine_version = "7.1"
  node_type      = "db.r7g.2xlarge"
  num_shards     = 1
  
  # Parameter group
  create_parameter_group = false
  parameter_group_name   = "default.memorydb-redis7.search.preview "
  ...
}
```

**Comment by jeferramirez** [comment]
> I don't think you are following the docs correctly, I think you need to do:
> 
> ```terraform
> module "memory_db" {
>   source = "terraform-aws-modules/memory-db/aws"
> 
> 
>   engine_version = "7.1"
>   node_type      = "db.r7g.2xlarge"
>   num_shards     = 1
>   
>   # Parameter group
>   create_parameter_group = false
>   parameter_group_name   = "default.memorydb-redis7.search.preview "
>   ...
> }
> ```

I'm getting this error from terraform apply : InvalidParameterValueException: Parameter Group ID specified is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, dots and hyphens; and must not end with a dot or hyphen or contain two consecutive dots or hyphens.

**Comment by bryantbiggs** [comment]
oh, there was an extra whitespace character in the snippet I provided - corrected

**Comment by bryantbiggs** [comment]
also, you shouldn't need `parameter_group_family = "memorydb_redis7"` - thats only used if you are creating a parameter group

**Comment by bryantbiggs** [comment]
awesome! closing this out then, thanks all!
